// Code generated by "stringer -type=BlockType -output=block_type_string.go"; DO NOT EDIT.

package blocktype

import "fmt"

const (
	_BlockType_name_0 = "InterfaceDescription"
	_BlockType_name_1 = "SimplePacketNameResolutionInterfaceStatisticsEnhancedPacket"
	_BlockType_name_2 = "SectionHeader"
)

var (
	_BlockType_index_0 = [...]uint8{0, 20}
	_BlockType_index_1 = [...]uint8{0, 12, 26, 45, 59}
	_BlockType_index_2 = [...]uint8{0, 13}
)

func (i BlockType) String() string {
	switch {
	case i == 1:
		return _BlockType_name_0
	case 3 <= i && i <= 6:
		i -= 3
		return _BlockType_name_1[_BlockType_index_1[i]:_BlockType_index_1[i+1]]
	case i == 168627466:
		return _BlockType_name_2
	default:
		return fmt.Sprintf("BlockType(%d)", i)
	}
}
